language: bash
services: docker
sudo: required

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - docker build -t napnap75/rpi-mariadb:latest .
  - docker images

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push napnap75/rpi-mariadb:latest
  - export CURRENTDATE=$(date +%y%m%d)
  - docker tag napnap75/rpi-mariadb:latest napnap75/rpi-mariadb:$CURRENTDATE
  - docker push napnap75/rpi-mariadb:$CURRENTDATE
  
